theme = "everforest_transparent"

[keys.normal.space]
";" = [":w", ":sh make && $exec"]

[keys.normal]
i = [":indent-style t", "insert_mode"]
v = [":indent-style t", "select_mode"]

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1
